# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170421_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='salt',
            field=models.CharField(default='$2b$12$jP5X3r5Ji0g8BtDRyfYee.', max_length=100),
        ),
    ]
