# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170422_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='authorized_files', to='main.User'),
        ),
        migrations.AlterField(
            model_name='file',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_files', to='main.Folder'),
        ),
        migrations.AlterField(
            model_name='file',
            name='stars',
            field=models.ManyToManyField(null=True, related_name='starred_files', to='main.User'),
        ),
    ]
