# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170422_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='stars',
            field=models.ManyToManyField(related_name='starred_files', to='main.User'),
        ),
    ]
