# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 16:33
from __future__ import unicode_literals

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170422_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_data',
            field=models.FileField(upload_to=apps.main.models.get_upload_file_name),
        ),
    ]
